import { InputConfig } from "../ui/dashboard/form-field";
import {
  ChartBarIcon,
  CakeIcon,
  ExclamationTriangleIcon,
  EyeDropperIcon,
  BeakerIcon,
  ShieldCheckIcon,
  ArchiveBoxIcon,
  RocketLaunchIcon,
  ShieldExclamationIcon,
  ArrowRightStartOnRectangleIcon,
  BellAlertIcon,
  WrenchScrewdriverIcon,
  TrophyIcon,
  PencilSquareIcon,
  CheckBadgeIcon,
} from "@heroicons/react/24/outline";

export const NUMERIC_INPUT_CONFIGS = [
  // Numeric inputs
  {
    name: "census",
    label: "Census",
    type: "number",
    icon: ChartBarIcon,
    placeholder: "Enter census count",
  },
  {
    name: "tpn_count",
    label: "TPN Count",
    type: "number",
    icon: CakeIcon,
    placeholder: "Enter TPN count",
  },
  {
    name: "haz_count",
    label: "Hazardous Count",
    type: "number",
    icon: ExclamationTriangleIcon,
    placeholder: "Enter hazardous count",
  },
  {
    name: "non_sterile_count",
    label: "Non-Sterile Count",
    type: "number",
    icon: EyeDropperIcon,
    placeholder: "Enter non-sterile count",
  },
  {
    name: "complex_preps_count",
    label: "Complex Preps",
    type: "number",
    icon: BeakerIcon,
    placeholder: "Enter complex preps count",
  },
  {
    name: "missed_dispense_prep",
    label: "Dispense Preps",
    type: "number",
    icon: PencilSquareIcon,
    placeholder: "Enter missed dispense preps",
  },
  {
    name: "missed_dispense_check",
    label: "Dispense Checks",
    type: "number",
    icon: CheckBadgeIcon,
    placeholder: "Enter missed dispense checks",
  },
] as const satisfies readonly InputConfig[];

export const TEXT_INPUT_CONFIGS = [
  // Text inputs
  {
    name: "safety_morning",
    label: "Safety - Morning",
    type: "textarea",
    icon: ShieldCheckIcon,
    placeholder: "Safety updates...",
  },
  {
    name: "inventory_morning",
    label: "Inventory - Morning",
    type: "textarea",
    icon: ArchiveBoxIcon,
    placeholder: "Inventory notes...",
  },
  {
    name: "go_lives_morning",
    label: "Go Lives - Morning",
    type: "textarea",
    icon: RocketLaunchIcon,
    placeholder: "Go live updates...",
  },
  {
    name: "barriers_morning",
    label: "Barriers - Morning",
    type: "textarea",
    icon: ShieldExclamationIcon,
    placeholder: "Barriers...",
  },
  {
    name: "pass_off_morning",
    label: "Pass Off - Morning",
    type: "textarea",
    icon: ArrowRightStartOnRectangleIcon,
    placeholder: "Pass-off updates...",
  },
    {
    name: "unresolved_issues_morning",
    label: "Unresolved Issues - Morning",
    type: "textarea",
    icon: BellAlertIcon,
    placeholder: "Unresolved Issues...",
  },
   {
    name: "opportunities_morning",
    label: "Opportunities - Morning",
    type: "textarea",
    icon: WrenchScrewdriverIcon,
    placeholder: "Opportunity updates...",
  },
  {
    name: "shout_outs_morning",
    label: "Shout Outs - Morning",
    type: "textarea",
    icon: TrophyIcon,
    placeholder: "Shout Outs...",
  },


  {
    name: "safety_noon",
    label: "Safety - Noon",
    type: "textarea",
    icon: ShieldCheckIcon,
    placeholder: "Safety updates...",
  },
  {
    name: "inventory_noon",
    label: "Inventory - Noon",
    type: "textarea",
    icon: ArchiveBoxIcon,
    placeholder: "Inventory notes...",
  },
  {
    name: "go_lives_noon",
    label: "Go Lives - Noon",
    type: "textarea",
    icon: RocketLaunchIcon,
    placeholder: "Go live updates...",
  },
  {
    name: "barriers_noon",
    label: "Barriers - Noon",
    type: "textarea",
    icon: ShieldExclamationIcon,
    placeholder: "Barriers...",
  },
  {
    name: "pass_off_noon",
    label: "Pass Off - Noon",
    type: "textarea",
    icon: ArrowRightStartOnRectangleIcon,
    placeholder: "Pass-off updates...",
  },
  {
    name: "unresolved_issues_noon",
    label: "Unresolved Issues - Noon",
    type: "textarea",
    icon: BellAlertIcon,
    placeholder: "Unresolved Issues...",
  },
  {
    name: "opportunities_noon",
    label: "Opportunities - Noon",
    type: "textarea",
    icon: WrenchScrewdriverIcon,
    placeholder: "Opportunity updates...",
  },
  {
    name: "shout_outs_noon",
    label: "Shout Outs - Noon",
    type: "textarea",
    icon: TrophyIcon,
    placeholder: "Shout Outs...",
  },


  {
    name: "safety_night",
    label: "Safety  - Night",
    type: "textarea",
    icon: ShieldCheckIcon,
    placeholder: "Safety updates...",
  },
  {
    name: "inventory_night",
    label: "Inventory - Night",
    type: "textarea",
    icon: ArchiveBoxIcon,
    placeholder: "Inventory notes...",
  },
  {
    name: "go_lives_night",
    label: "Go Lives - Night",
    type: "textarea",
    icon: RocketLaunchIcon,
    placeholder: "Go live updates...",
  },
  {
    name: "barriers_night",
    label: "Barriers - Night",
    type: "textarea",
    icon: ShieldExclamationIcon,
    placeholder: "Barriers...",
  },
  {
    name: "pass_off_night",
    label: "Pass Off - Night",
    type: "textarea",
    icon: ArrowRightStartOnRectangleIcon,
    placeholder: "Pass-off updates...",
  },
  {
    name: "unresolved_issues_night",
    label: "Unresolved Issues - Night",
    type: "textarea",
    icon: BellAlertIcon,
    placeholder: "Unresolved Issues...",
  },
  {
    name: "opportunities_night",
    label: "Opportunities - Night",
    type: "textarea",
    icon: WrenchScrewdriverIcon,
    placeholder: "Opportunity updates...",
  },
  {
    name: "shout_outs_night",
    label: "Shout Outs - Night",
    type: "textarea",
    icon: TrophyIcon,
    placeholder: "Shout Outs...",
  },
] as const satisfies readonly InputConfig[];
